### ISSUE TITLE
Updated stream properties are not sent before other data until it is flushed

### ISSUE THREAD

**Issue by theoengland** [quixai/quix-streams#11]
Ok, that title is bad, but the idea around properties of streams is that they have a bit of delay before gettings sent to avoid sending it multiple times for each change in a very short interval.

Once this interval elapses ( or someone calls .Flush()), it gets set as the latest set of properties and sent to the wire.

In addition to this, we have a certain period of properties re-broadcast. To avoid re-broadcasting it on its own, filling up the topic with nothing else, we have logic to only do this if there is other message type to send, like parameter data.
In this scenario, the properties gets sent, then the actual data if the re-broadcast logic is fulfilled.

Now, the problem is that when initially a stream is created, properties are set and data gets sent, the re-broadcast logic is triggered, but with the initial null stream properties instead of the configured one, as the properties flush is not yet triggered.

**Comment by peter-quix** [comment]
moved to https://github.com/quixio/quix-streams-dotnet/issues/14
