### ISSUE TITLE
Remove value typed properties on TimeseriesDataTimestamp object

### ISSUE THREAD

**Issue by tomas-quix** [quixai/quix-streams#127]
**Is your feature request related to a problem? Please describe.**
```
old_way = row.parameters["EngineRPM"].numeric_value
new_way = row.parameters["EngineRPM"]
```

**Comment by peter-quix** [comment]
Only relevant for C#, which can be found here https://github.com/quixio/quix-streams-dotnet. C# already has a .value however so I'm closing this without replicating in new repo
