### ISSUE TITLE
Split Kafka logic from QuixStreams.Streaming and QuixStreams.Telemetry

### ISSUE THREAD

**Issue by theoengland** [quixai/quix-streams#13]
Maybe in the same go rename Quix.Process to Quix.Telemetry

Essentially your layer 2 introduces telemetry, it is a whole lot more descriptive than "Process"

**Comment by peter-quix** [comment]
Closing, for the time being in 0.6.0 C# (see at https://github.com/quixio/quix-streams-dotnet) Kafka became more ingrained into the library
