### ISSUE TITLE
Merge events endpoint with Timeseries endpoint

### ISSUE THREAD

**Issue by tomas-quix** [quixai/quix-streams#138]
**Is your feature request related to a problem? Please describe.**
Our platform requires Quix customer schema. If not used, it is not that helpful. 

**Describe the solution you'd like**
Custom events get materialised as tabular data.

**Additional context**
https://quix.notion.site/Merge-events-and-time-series-endpoints-d5ea49e51492498e90d2935decc64c24?pvs=4

**Comment by peter-quix** [comment]
C# codebase moved
