### ISSUE TITLE
CheckIfClosed improvement

### ISSUE THREAD

**Issue by theoengland** [quixai/quix-streams#16]
This could have very serious performance implications on writing because it is executed in every single packet sent to the topic.

Probably we should avoid lock every time, and only do the lock when we are in an actual Closing state.

![image](https://user-images.githubusercontent.com/5121621/203817757-3ee96472-3206-4964-9add-24344f37a5f6.png)

**Comment by peter-quix** [comment]
moved to https://github.com/quixio/quix-streams-dotnet/issues/15
