### ISSUE TITLE
Topic name property available in topic and stream objects

### ISSUE THREAD

**Issue by JotaBlanco** [quixai/quix-streams#24]
**Is your feature request related to a problem? Please describe.**
When creating a same callback to react to different topics, I'd like some times to have the topic name information within the callback function (for example, to create a TAG in the output informing about the input topic that is behind that specific message). 

**Describe the solution you'd like**
I'd like to have access to the topic name property through the InputTopic, OutputTopic, StreamReader and StreamWriter objects. So, same as I can do `input_stream.stream_id` I'd also like that `input_topic.topic_id` and `input_stream.topic_id` were possible.

**Comment by peter-quix** [comment]
We'll explore the option to improve the callbacks to provide more details such as this.

**Comment by peter-quix** [comment]
After https://github.com/quixio/quix-streams/pull/39, in python the callbacks will have the following parameters:
1) Input/Output topic
2) Stream
3) Other (such as Data, end type, etc)

In C# it is using Eventhandler<args> signature, giving option to subscribe to event with (sender, args) => .... signature, where args has properties relevant for the event, such as Topic, Stream, Data.

I will see if I can add some details to the topic.

**Comment by JotaBlanco** [comment]
I didn't quite understand what you mean with the callback. Is the TopicConsumer/TopicProducer class going to have a topic_id method?

**Comment by peter-quix** [comment]
Closing ticket, for now this should be sorted in C# which moved to https://github.com/quixio/quix-streams-dotnet
For new python this isn't likely an issue
