### ISSUE TITLE
SDK breaks when handling in array

### ISSUE THREAD

**Issue by SteveRosam** [quixai/quix-streams#302]
The data being published (via the SDK) from the previous node in the pipeline is:

`[[6], [7], [8], [9], [10]]`

The error I get is:

`TypeError: Row value must be a dict, but got "<class 'list'>"`

Suggestion is: throw an error on publish so the data never enters the topic. 

Workaround: I have to delete my topic now.

Slack discussion: https://stream-processing.slack.com/archives/C033BGFD1L6/p1709210724220199

**Comment by ghost** [comment]
Fixed in [v2.3.2](https://github.com/quixio/quix-streams/releases/tag/v2.3.2)
