### ISSUE TITLE
2.3.1 typings

### ISSUE THREAD

**Issue by SteveRosam** [quixai/quix-streams#303]
`pip install quixstreams==2.2.1a0 --force` = no red lines
`pip install quixstreams==2.3.1 --force` = red lines

![image](https://github.com/quixio/quix-streams/assets/100689438/e81b7f6a-4b82-45ac-803b-e63313ed7979)

**Comment by ghost** [comment]
Hi @SteveRosam , thanks for submitting the issue!

There's a PR merged recently (https://github.com/quixio/quix-streams/pull/292) that will fix that.

The `2.3.2` release is waiting for a couple more updates, and we plan to have it soon.

I will close the issue when the release is out.

**Comment by ghost** [comment]
Fixed in [v2.3.2](https://github.com/quixio/quix-streams/releases/tag/v2.3.2)
