### ISSUE TITLE
Better documentation of MessageContext

### ISSUE THREAD

**Issue by merlin-quix** [quixai/quix-streams#319]
Recently, in the Quix community Slack, I was made aware of getting the Kafka timestamp using `message_context().timestamp`

I tried to find some more documentation on this property, but I only found some a minimal reference information: https://quix.io/docs/quix-streams/api-reference/quixstreams.html#quixstreamsmodelsmessagecontext

It would be good to have some more thorough user-friendly documentation with usage examples.

**Comment by ghost** [comment]
Hey @merlin-quix !
We're working on the new docs in [this PR](https://github.com/quixio/quix-streams/pull/315)

The message context is now covered in [this section](https://github.com/quixio/quix-streams/blob/1cd6c4afd2fcf740dd17ae6897174d36fdf6c34f/docs/processing.md#accessing-kafka-keys-and-metadata)

Could you please tell if it makes it more clear?

Thanks!

**Comment by ghost** [comment]
Hey @merlin-quix, 
The new docs are released in https://github.com/quixio/quix-streams/pull/315

I'm going to close this issue.

If you think that the MessageContext needs more docs, please reopen it.
