### ISSUE TITLE
Readme contains 404's

### ISSUE THREAD

**Issue by sionsmith** [quixai/quix-streams#326]
**Tell us about the bug**
Readme contains a bunch of great tutorials but links are pointing to the wrong place.

**Comment by ghost** [comment]
Hey Sion!
Thanks a lot for creating the issue and the PR.

It's fixed in https://github.com/quixio/quix-streams/pull/328.

I'll close the https://github.com/quixio/quix-streams/pull/327 (in 328 the links lead to `quix.io/docs` instead of github)
