### ISSUE TITLE
Add API to provide SASL and SSL authentication 

### ISSUE THREAD

**Issue by ghost** [quixai/quix-streams#354]
# Why?
To provide SASL and SSL authentication configs, users need to do it twice for Producer and Consumer via `producer_extra_config` and `consumer_extra_config`.
It may lead to duplicating the same configs and forgetting to pass them to both places is easy.

# What?
Add a way to provide authentication configs once on the Application level.
These configs will be applied to the internal producer and consumer, as well as the ones created using `Application.get_producer()` API.

Specifically, users should be able to provide these configs via Application parameters:
- `ssl.*` - via `ssl_config: SSLConfig` param
- `sasl.*` - via `sasl_config: SASLConfig` param
- `security.protocol` - via `security_protocol: str` parameter

# How?
- Use `pydantic` to describe `SSLConfig` and `SASLConfig` models to incorporate all individual values
- Ignore the non-provided values to rely on `librdkafka`'s defaults
- Values provided via `producer_extra_config` and `consumer_extra_config` should override the above
- If `quix_sdk_token` is passed, these parameters should be ignored

**Comment by tim-quix** [comment]
completed with PR #371
