### ISSUE TITLE
Rename Application parameter from loglevel to log_level

### ISSUE THREAD

**Issue by stereosky** [quixai/quix-streams#404]
Setting the log level in the `Application` object is done with the parameter `loglevel`. Is there a reason why it's named as such when it seems for consistency `log_level` would be more appropriate?

We could have:
```python
app = Application(
    broker_address="localhost:9092",
    consumer_group="group_a",
    auto_offset_reset="latest",
    log_level="DEBUG"
)
```

Rather than:
```python
app = Application(
    broker_address="localhost:9092",
    consumer_group="group_a",
    auto_offset_reset="latest",
    loglevel="DEBUG"
)
```

**Comment by ghost** [comment]
Hey @stereosky !
There's no particular reason why it's named `loglevel` vs `log_level` to be honest :)
I'd keep the current name to avoid backward compatibility issues.
