### ISSUE TITLE
 `StreamingDataFrame` method parameters no longer recognized

### ISSUE THREAD

**Issue by tim-quix** [quixai/quix-streams#452]
This bug was introduced in version `2.9.0`.

With sinks, `SDF` "locking" was introduced, blocking any additional operations being added to one after `SDF.sink()` was called.

Unfortunately, this caused some function arguments to not be recognized correctly (for things like autocomplete/type hinting). Example:

`sdf.drop("col_a", error="raise")` will now say that `error` is an unknown parameter.

This is confirmed to show in Pycharm, but may occur in other IDE's.

**Comment by ghost** [comment]
Thanks for the report!
I'll have a look.
Probably the `@_ensure_unlocked` decorator messed up the typings. 
Also, after #419 we'll need to update this code anyway.

**Comment by tim-quix** [comment]
fixed by #419
