### ISSUE TITLE
Drop support for python3.8 in the next major release

### ISSUE THREAD

**Issue by ghost** [quixai/quix-streams#473]
Python3.8 EOL is in October 2024, and it won't receive security updates anymore.
We can also drop the support and increase the minimal version to 3.9.

**Comment by gwaramadze** [comment]
Once Python 3.8 support is dropped, the contents of this commit should be reverted: https://github.com/quixio/quix-streams/pull/449/commits/b67ecf86266d5ad59471fa3db77af96dadbdebbb

The commit itself was squashed so it will have to be done manually.
