### ISSUE TITLE
Feature: Sliding Windows

### ISSUE THREAD

**Issue by ghost** [quixai/quix-streams#485]
Add support for Sliding Windows. 

Sliding Windows are fixed-time windows determined by the record timestamps. 
For example, calculating the average sum over the last 5 minutes requires sliding windows.
Joins also use sliding windows.

More details and API examples will be added later.

Relates to #484

**Comment by macanderson** [comment]
This is also called a "hopping" window in the world of Apache flink and is definitely a very important feature for my work thanks for working on this!

**Comment by ghost** [comment]
Released in 3.2.0
