### ISSUE TITLE
AVRO Support

### ISSUE THREAD

**Issue by theoengland** [quixai/quix-streams#5]
Enable Avro support - https://github.com/apache/avro

**Comment by theodore-evans** [comment]
Is there a timeline for this? It is currently one of our barriers to adoption.

**Comment by peter-quix** [comment]
> Is there a timeline for this? It is currently one of our barriers to adoption.

We're looking into supporting this in our python rewrite maybe as early as a month or two., depending on the difficulty of enabling it.
However we're planning on supporting it for sure in 2024 for both C# and Python, possibly as early as Q1.

**Comment by peter-quix** [comment]
C# Migrated to new repo, moving ticket to https://github.com/quixio/quix-streams-dotnet/issues/8
Python specific support is on the roadmap which will be updated later.
