### ISSUE TITLE
from_dataframe() brakes with nulls in time column

### ISSUE THREAD

**Issue by JotaBlanco** [quixai/quix-streams#54]
**Tell us about the bug**
[from_dataframe() ](https://github.com/quixio/quix-streams/blob/main/src/PythonClient/src/quixstreams/models/timeseriesdataraw.py#L134) conversion seems to break if there are nulls in the time column of the dataframe.

**What did you expect to see?**
Here, as with any null dealing situation, there is a decision to make:

- Drop the rows with nulls in the time column:
`dataframe = dataframe.dropna(subset=time_label)`

- Extrapolate the nulls in the time columns using surrounding values:
`dataframe[time_label] = dataframe[time_label].interpolate(method='linear')`

**Comment by peter-quix** [comment]
Thinking best would be to throw an exception rather than silently ommitting // setting an  artificial value

**Comment by peter-quix** [comment]
No longer relevant, new python code is not working the same way
