### ISSUE TITLE
from_dataframe() cannot handle complex numbers

### ISSUE THREAD

**Issue by JotaBlanco** [quixai/quix-streams#55]
**Tell us about the bug**
from_dataframe() breaks when dealing with columns with complex numbers:

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<timed eval> in <module>

<ipython-input-11-e56d4825e396> in from_dataframe(data_frame, epoch)
    111             isnumeric = (label_type == int or label_type == float or label_type == complex)
    112             if isnumeric:
--> 113                 if math.isnan(content):
    114                     continue  # ignore it, as panda uses NaN instead of None, unable to detect difference
    115                 if panda_col_label.startswith('TAG__'):  # in case user of lib didn't put it in quote don't throw err

TypeError: can't convert complex to float`

**Comment by peter-quix** [comment]
Please provide a code sample that can be used to reproduce the issue,

Also, are those line numbers provided by your IDE for the lib's codebase or some version of it that you use? I can't match it with any source code we have.

**Comment by JotaBlanco** [comment]
hey @peter-quix, yep I was using a notebook for some of these tests. You can find it here: https://github.com/quixio/quix-streams-to_dataframe_tests/blob/main/src/PythonClient/tests/quixstreams/manual/from_dataframe.ipynb

**Comment by peter-quix** [comment]
No longer relevant, new python code is not working the same way
