### ISSUE TITLE
Sink quits immediately

### ISSUE THREAD

**Issue by markuspinter** [quixai/quix-streams#550]
**Tell us about the bug**
I'm using sdf.sink() with a custom batching sink. When I'm starting it it immediately quits with exit code 0

**What did you expect to see?**
It should keep running and process the batch regularily

**What version of the library are you using?**
quixstreams 2.11.1

The env setup was generated by your quix cli tool, so I'm using redpanda as the kafka broker

**Workaround?**
Using the old school update function

**Anything else we should know?**
Here's the sample code 

```python
import os

from dotenv import load_dotenv
from quixstreams import Application

from src.database_sink import DatabaseSink
from src.settings import DatabaseSettings

load_dotenv()


app = Application(
    consumer_group="destination-v1",
    auto_offset_reset="latest",
    auto_create_topics=True,
)

input_topic = app.topic(os.environ["input"])


if __name__ == "__main__":
    database_settings = DatabaseSettings()

    db_sink = DatabaseSink(database_settings=database_settings)

    sdf = app.dataframe(input_topic)
    sdf = sdf.print()

    # call the sink function for every message received.
    sdf.sink(db_sink)
```

I also tried setting the `commit_every` param but still the same issue

DatabaseSink:

```python
import json
from typing import Any, Callable

import psycopg
from quixstreams.sinks.base.sink import BatchingSink, SinkBatch

from src.database import insert_message
from src.settings import DatabaseSettings


class DatabaseSink(BatchingSink):
    def __init__(
        self,
        database_settings: DatabaseSettings,
        key_serializer: Callable[[Any], str] = str,
        value_serializer: Callable[[Any], str] = json.dumps,
    ):
        """
        A base database sink that writes data from all assigned partitions to a database.
        """
        super().__init__()
        self._key_serializer = key_serializer
        self._value_serializer = value_serializer
        self.database_settings = database_settings

    def write(self, batch: SinkBatch):
        with psycopg.connect(
            host=self.database_settings.host,
            port=self.database_settings.port,
            dbname=self.database_settings.database_name,
            user=self.database_settings.user,
            password=self.database_settings.password,
        ) as conn:

            for item in batch:
                print(item.value)
                insert_message(
                    item.value,
                    conn=conn,
                    schema_name=self.database_settings.schema_name,
                )

```
The database settings is a pydantic settings object, and the insert_message is an already tested function that insert into the database. Using sdf.update() this works, but with the sink() function it quits immediately.

Do you have a guess what the problem could be? 
Thank you so much!

**Comment by ghost** [comment]
Hey @markuspinter,

The `app.run(sdf)` line is missing at the end, so it exits immediately.  
Adding it after `sdf.sink(db_sink)` should fix the problem.

We missed it in the Sinks docs, so I'll fix it 👍 

Thanks for your report!

**Comment by markuspinter** [comment]
Thanks Daniil for the quick response!

I originally also tried that, but then I got an error that no context is assigned or something. Unfortunately I can't reproduce it anymore because it works now all of a sudden. Maybe some weird state was cached in the docker image because in between I did a `docker compose down` and `docker compose up` again. 👍
