### ISSUE TITLE
Timeseries messages not sent when flush called immediately after buffering.

### ISSUE THREAD

**Issue by harisbotic** [quixai/quix-streams#88]
If you try to send timeseries messages through a buffer and then immediately call the flush function, the messages that were most recently added to the buffer may not get sent. 
However, if I **sleep** for even a 0.1 seconds before calling the flush function, all messages are sent as expected.

The same behaviour happens in both C# and python client.

Reproducible example in [Benchmark kafka libraries repo](https://github.com/quixio/benchmarks-kafka-libraries)

**Comment by tomas-quix** [comment]
Merged.
